workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.aifun.dateideas.planadate
        code_signing_identity: "iPhone Developer"  # Add this line
        provisioning_profiles:
          com.aifun.dateideas.planadate: "SoulPlan AI Fun Date Ideas Development Profile"  # Add your profile name
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.aifun.dateideas.planadate"
