workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      ios_signing:
        provisioning_profiles:
          - "SoulPlan AI Fun Date Ideas last minute date idea ios_app_development 1732825290"
        certificates:
          - name: ios_development
            reference: development
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.aifun.dateideas.planadate"
    scripts:
      - name: Set up code signing settings
        script: |
          keychain initialize
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter packages pub get
      - name: Install pods
        script: |
          cd ios
          pod repo update
          pod install
      - name: Flutter build iOS
        script: |
          flutter build ipa --debug \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
