source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'

ENV['FLUTTER_FRAMEWORK_DIR'] = File.expand_path(File.join('..', 'Flutter'), __FILE__)

install! 'cocoapods',
   :disable_input_output_paths => true,
   :deterministic_uuids => false

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

# Previous configuration remains the same until the Runner target

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Firebase pods
  pod 'Firebase/Storage', '10.10.0'
  pod 'Firebase/Auth', '10.10.0'
  pod 'Firebase/AppCheck', '10.10.0'
  pod 'Firebase/Firestore', '10.10.0'
  pod 'Firebase/Crashlytics', '10.10.0'
  pod 'Firebase/Analytics', '10.10.0'

  # Google Ads
  pod 'Google-Mobile-Ads-SDK', '~> 10.9.0'


  # Facebook
  pod 'FBAudienceNetwork'

  # Specify darwin path for webview
pod 'webview_flutter_wkwebview', :path => '.symlinks/plugins/webview_flutter_wkwebview/darwin'


  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['VALID_ARCHS'] = 'arm64'
      config.build_settings['ONLY_ACTIVE_ARCH'] = config.debug? ? 'YES' : 'NO'

      
      # Enhanced webview configuration
      if target.name == 'webview_flutter_wkwebview'
        config.build_settings['CONFIGURATION_BUILD_DIR'] = '${PODS_CONFIGURATION_BUILD_DIR}'
        config.build_settings['DEFINES_MODULE'] = 'YES'
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] = '$(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/webview_flutter_wkwebview"'
      end
      
      if target.respond_to?(:product_type) && target.product_type == "com.apple.product-type.bundle"
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['WRAPPER_EXTENSION'] = 'bundle'
        config.build_settings['GENERATE_INFOPLIST_FILE'] = 'YES'
      end
    end
  end
end

