source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

# Your existing configuration remains the same until post_install

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] = [
        '$(inherited)',
        '$(PODS_ROOT)/Flutter',
        '$(PODS_CONFIGURATION_BUILD_DIR)',
        '$(PODS_ROOT)/../Flutter',
        '$(SRCROOT)/../Flutter'
      ]

      # Enhanced privacy bundle handling
      if target.respond_to?(:product_type) && target.product_type == "com.apple.product-type.bundle"
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['WRAPPER_EXTENSION'] = 'bundle'
        config.build_settings['SKIP_INSTALL'] = 'NO'
        config.build_settings['GENERATE_INFOPLIST_FILE'] = 'YES'
      end

      # Enhanced localization settings
      config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
      config.build_settings['SWIFT_EMIT_LOC_STRINGS'] = 'YES'
      config.build_settings['DEVELOPMENT_LANGUAGE'] = 'en'
      config.build_settings['SUPPORTED_LOCALES'] = [
        'en_US', 'en_GB', 'en_CA', 'ko', 'zh', 'es',
        'fr', 'de', 'hi', 'pt', 'pt_BR', 'ru',
        'in', 'fil', 'bn', 'af', 'nl'
      ]
      config.build_settings['LOCALIZED_STRING_MACRO_NAMES'] = ['NSLocalizedString']
      config.build_settings['LOCALIZATION_PREFERS_STRING_CATALOGS'] = 'YES'

      config.build_settings['DERIVED_DATA_DIR'] = File.expand_path('~/Downloads/KaynellOS/ai_date/ios/DerivedData')
      config.build_settings['CONFIGURATION_BUILD_DIR'] = File.expand_path('~/Downloads/KaynellOS/ai_date/ios/Build/Products')
      config.build_settings['CONFIGURATION_TEMP_DIR'] = File.expand_path('~/Downloads/KaynellOS/ai_date/ios/Build/Intermediates')
      config.build_settings['OTHER_LDFLAGS'] = ['$(inherited)', '-framework', 'Flutter']
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
    end
  end
end
